# Url
url: https://www.diogorusso.com
baseurl: "/journal"

# Sass
sass:
  style: :compressed
#theme
remote_theme: 'diogorusso/diogorusso.jekyll.theme'

paginate: 5
plugins: [jekyll-paginate,jekyll-remote-theme]

paginate_path: "/page:num/"

sidebar_title: "Journal"
sidebar_items:
  - title: "Ideas"
    url: "hello"
  - title: "Learn"
    url: "hello"
  - title: "Lab"
    url: "hello"

# Info
author: "Diogo Russo"
title: "Diogo Russo - UX + Product Design"
description: "I'm a designer, artist and storyteller, an optimist dedicated to help bringing ideas to life."
# description: "I like sharing inspiration, resources and insights of what it takes to bring ideas to life."
keywords: "Diogo Russo, Product Desig, UX Design, Graphic Design, Visual Arts"

# Media CDN (cloudinary)
cdn: /journal/assets/
static: /journal/assets/
profile: about/bio/diogorusso.jpg
icIco: favicon.ico #root folder
icSvg: favicon.svg #root folder
ic512x512: favicons/icon-512x512.png
ic310x310: favicons/icon-310x310.png
ic192x192: favicons/icon-192x192.png
ic180x180: favicons/icon-180x180.png
ic150x150: favicons/icon-150x150.png
ic144x144: favicons/icon-144x144.png
ic70x70: favicons/icon-70x70.png
ic310x150: favicons/icon-310x150.png

# Social Profiles
social:
  - title: behance
    url: "https://www.behance.net/diogorusso"
  - title: linkedin
    url: "https://www.linkedin.com/in/diogorusso/?locale=en_US"
  - title: instagram
    url: "https://www.instagram.com/diogorusso/"

#  post permalink
permalink: /:categories/:slug

# collections:
#   design:
#     output: true
#     # permalink: /design/:path
#   work:
#     output: true

#     permalink: /:path

defaults:
  - scope:
      path: ""
      type: "work"
    values:
      layout: default

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "vendor",
  "README.md",
  "LICENSE",
  "reveal.js/test",
  "reveal.js/index.html",
  "reveal.js/README.md",
  "reveal.js/bower.json",
  "reveal.js/Gruntfile.js",
  "reveal.js/CONTRIBUTING.md",
  "reveal.js/LICENSE",
  "reveal.js/package.json"
]

